# Generated by Django 4.2.1 on 2023-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
